# Generated by Django 4.2.3 on 2023-07-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_task_edited_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='edited_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
